import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

const sfProDisplayLight = localFont({
  src: "/fonts/sf-pro-display-light.woff",
  variable: "--light",
  weight: "600",
  display: "swap",
  preload: true,
});

const sfProDisplayRegular = localFont({
  src: "/fonts/sf-pro-display-regular.woff",
  variable: "--regular",
  weight: "700",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "WortKraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
      <body
        className={`body ${sfProDisplayLight.variable} ${sfProDisplayRegular.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
